FROM ghcr.io/osgeo/gdal:ubuntu-full-3.11.3

WORKDIR /app

ARG TARGETARCH

# Setup python and poetry
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv

# Installing poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN $HOME/.local/bin/poetry self add "poetry-plugin-export"

# Getting s5cmd
RUN apt-get install -y wget
RUN if [ "$TARGETARCH" = "arm64" ]; then \
        wget -O s5cmd.tar.gz https://github.com/peak/s5cmd/releases/download/v2.3.0/s5cmd_2.3.0_Linux-arm64.tar.gz; \
    elif [ "$TARGETARCH" = "amd64" ]; then \
        wget -O s5cmd.tar.gz https://github.com/peak/s5cmd/releases/download/v2.3.0/s5cmd_2.3.0_Linux-64bit.tar.gz; \
    else \
        exit 1; \
    fi
RUN tar -xzf s5cmd.tar.gz -C /bin s5cmd

# Copying edk metadata and requirement files
WORKDIR /app/earth-data-kit
COPY pyproject.toml /app/earth-data-kit/pyproject.toml
COPY poetry.lock /app/earth-data-kit/poetry.lock
COPY README.md /app/earth-data-kit/README.md
COPY LICENSE.md /app/earth-data-kit/LICENSE.md
RUN $HOME/.local/bin/poetry export --only main --format requirements.txt --without-hashes --output /app/edk-requirements.txt

# Installing aws cli
RUN apt-get install -y unzip

RUN if [ "$TARGETARCH" = "arm64" ]; then \
        wget -O "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"; \
    elif [ "$TARGETARCH" = "amd64" ]; then \
        wget -O "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"; \
    else \
        exit 1; \
    fi

RUN unzip awscliv2.zip
RUN ./aws/install

# Copying edk codebase
COPY ./earth_data_kit /app/earth-data-kit/earth_data_kit

COPY entrypoint.release.sh /app/entrypoint.release.sh
RUN chmod +x /app/entrypoint.release.sh

WORKDIR /app/workspace

# Path is added in advance so during exec venv's python is used
ENV PATH="/opt/venv/bin:${PATH}"

ENTRYPOINT ["/app/entrypoint.release.sh"]