FROM ghcr.io/osgeo/gdal:ubuntu-full-3.11.3

WORKDIR /app

# Setup python and poetry
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv

# Installing poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN $HOME/.local/bin/poetry self add "poetry-plugin-export"

# Getting s5cmd
RUN apt-get install -y wget
RUN wget -O s5cmd.tar.gz https://github.com/peak/s5cmd/releases/download/v2.3.0/s5cmd_2.3.0_Linux-64bit.tar.gz
RUN tar -xzf s5cmd.tar.gz -C /bin s5cmd

# Copying edk metadata and requirement files
WORKDIR /app/earth-data-kit
COPY pyproject.toml /app/earth-data-kit/pyproject.toml
COPY poetry.lock /app/earth-data-kit/poetry.lock
COPY README.md /app/earth-data-kit/README.md
COPY LICENSE.md /app/earth-data-kit/LICENSE.md
RUN $HOME/.local/bin/poetry export --only main --format requirements.txt --without-hashes --output /app/edk-requirements.txt

# Installing aws cli
RUN apt-get install -y unzip
RUN wget -O "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip"
RUN unzip awscliv2.zip
RUN ./aws/install

COPY entrypoint.dev.sh /app/entrypoint.dev.sh
RUN chmod +x /app/entrypoint.dev.sh

WORKDIR /app/workspace

# Path is added in advance so during exec venv's python is used
ENV PATH="/opt/venv/bin:${PATH}"

ENTRYPOINT ["/app/entrypoint.dev.sh"]