services:
  edk:
    build:
      context: .
      dockerfile: Dockerfile.dev
    security_opt:
      - seccomp:unconfined
    container_name: edk
    tty: true
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ${WORKSPACE_DIR:-./workspace}:/app/workspace
      - ${DATA_DIR:-./data}:/app/data
      - ${AWS_CONFIG_DIR:-~./aws}:/root/.aws
      - ./earth_data_kit:/app/earth-data-kit/earth_data_kit
      - ./.venv:/opt/venv
