services:
  edk:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Needed for requirements.txt to work
        WORKSPACE_DIR: ${WORKSPACE_DIR}
    container_name: edk
    tty: true
    command: /bin/bash -c "pip install -e /app/earth-data-kit && tail -f /dev/null"
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - ${WORKSPACE_DIR:-./workspace}:/app/workspace
      - ${DATA_DIR:-./data}:/app/data
      - ${AWS_CONFIG_DIR:-~./aws}:/root/.aws
      - ./earth_data_kit:/app/earth-data-kit/earth_data_kit
